---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Include tasks for specific Linux release.
  include: '{{ ansible_system }}/{{ ansible_os_family }}.yml'

- name: Remove swapfile from /etc/fstab.
  mount:
    name: 'swap'
    fstype: 'swap'
    state: 'absent'

- name: Disable swap.
  command: 'swapoff -a'
  when: ansible_swaptotal_mb > 0

- name: Installs necessary runtime module.
  modprobe:
    name: '{{ item.name }}'
    state: 'present'
  loop: '{{ rke_module_dependents }}'
  when: item.create | default(true) | bool

- name: Transfer the module configuration file.
  template:
    src: 'rke_module.conf.j2'
    dest: '/etc/modules-load.d/rke.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure kernel parameters.
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  loop: '{{ rke_kernel_parameters }}'
  when: item.create | default(true) | bool

- name: SSH Server Configuration.
  lineinfile:
    state: 'present'
    dest: '/etc/ssh/sshd_config'
    regexp: '^{{ item.regexp }}'
    line: '{{ item.line }}'
  loop: '{{ rke_sshd_parameters }}'
  notify:
    - Restart sshd service.

- name: Flush handlers.
  meta: flush_handlers

- name: Include firewall tasks.
  include: '{{ ansible_system }}/firewall.yml'

- name: Installation the Rancher Kubernetes Engine version.
  include: '{{ ansible_system }}/install.yml'

- name: Creating prefix path for resources store.
  file:
    dest: '{{ rke_prefix }}'
    state: 'directory'
    owner: '{{ rke_arg.user }}'
    group: 'docker'
    mode: '0750'

- name: Deploying Kubernetes with RKE.
  include: '{{ ansible_system }}/up.yml'
  when:
    - rke_node_role == 'node'
    - rke_nodes[0] in ansible_default_ipv4.address
