---
- name: Include system variables.
  include_vars: '{{ ansible_system }}.yml'

- name: Include tasks for specific Operating System.
  include: '{{ ansible_system }}.yml'

- name: Registered with HashiCorp Consul.
  include: '{{ ansible_system }}/register.yml'
