---
- name: Install the dependents packages.
  yum:
    name: '{{ rke_kube_package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: rke_kube_soft_update
  until: rke_kube_soft_update is succeeded
  retries: 5
  delay: 2
