---
- name: Add Kubernetes YUM repositories.
  yum_repository:
    name: '{{ rke_kube_repo_name }}'
    description: '{{ rke_kube_repo_name }} YUM repository'
    file: '{{ rke_kube_repo_name }}'
    baseurl: '{{ rke_kube_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Kubernetes packages.
  yum:
    name: '{{ rke_kube_package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: rke_kube_soft_update
  until: rke_kube_soft_update is succeeded
  retries: 5
  delay: 2
